import type { Metadata } from "next";
import Image from "next/image";
import logo from "../../public/pokedex-logo.png";
import "./global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const renderHeader = () => {
  return <div className="h-10"></div>;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-blue-200 antialiased`}>
        <Image
          src={logo}
          width={500}
          height={500}
          alt="logo"
          className="mx-auto"
        />
        {children}
      </body>
    </html>
  );
}
